repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '.*\.py'
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: Linting
        name: Check LaTeX files
        entry: make lint
        pass_filenames: false
        language: system
