name: CI

on:
  pull_request:
  push:
    branches: [master]

# Source for the LaTeX docker container
# https://github.com/xu-cheng/texlive-action

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/xu-cheng/texlive-full:latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run -a
